export const TypographyStyleBase = {"fontFamily":"Lato","fontWeight":400,"lineHeight":"160%","fontSize":16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"};
export const TypographyStyleHeading = {"fontFamily":"BundesSans Office","fontWeight":700,"lineHeight":"115%","fontSize":34,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"};
export const TypographyStyleSubhead = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"115%","fontSize":19,"letterSpacing":"15%","paragraphSpacing":0,"textDecoration":"none","textCase":"uppercase"};
export const TypographyStyleH1 = {"fontFamily":"BundesSans Office","fontWeight":700,"lineHeight":"115%","fontSize":34,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"};
export const TypographyStyleH2 = {"fontFamily":"BundesSans Office","fontWeight":700,"lineHeight":"115%","fontSize":28,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"};
export const TypographyStyleH3 = {"fontFamily":"BundesSans Office","fontWeight":700,"lineHeight":"115%","fontSize":23,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"};
export const TypographyStyleH4 = {"fontFamily":"BundesSans Office","fontWeight":700,"lineHeight":"115%","fontSize":19,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"};
export const TypographyStyleMono = {"fontFamily":"Fira Mono","fontWeight":400,"lineHeight":"160%","fontSize":16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"};
export const TypographyStyleCaption = {"fontFamily":"Lato","fontWeight":400,"lineHeight":"160%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"};
export const TypographyFontFamilyBase = "Lato";
export const TypographyFontFamilyHeading = "BundesSans Office";
export const TypographyFontFamilyMono = "Fira Mono";
export const TypographyLineHeightBase = "160%";
export const TypographyLineHeightTighter = "140%";
export const TypographyLineHeightTightest = "115%";
export const TypographyFontWeightRegular = 400;
export const TypographyFontWeightMedium = 500;
export const TypographyFontWeightSemiBold = 600;
export const TypographyFontWeightBold = 700;
export const TypographyLetterSpacingBase = "0%";
export const TypographyLetterSpacingLooser = "15%";
export const TypographyParagraphSpacingNone = 0;
export const TypographyParagraphSpacingBase = 8;
export const TypographyTextCaseNone = "none";
export const TypographyTextCaseUppercase = "uppercase";
export const TypographyTextDecorationNone = "none";
export const SizeParameterFontSizeScaleFactor = 1.2;
export const SizeParameterFontSizeScaleFactorBelowOne = 1.15;
export const SizeParameterFontSizeBase = 16;
export const SizeParameterSpaceScaleFactor = 1.5;
export const SizeParameterSpaceScaleFactorBelowOne = 1.5;
export const SizeParameterSpaceBase = 24;
export const SizeChartWidth = 920;
export const SizeViewportLimit = 1440;
export const SizeMetaLabel = "Large";
export const SizeBorderWidthS = 0.5; // The smallest border size. Used for gridlines.
export const SizeBorderWidthM = 1; // The default border size. Used for axes borders, default data lines.
export const SizeBorderWidthL = 2; // A larger border size. Used for borders between filled elements.
export const SizeBorderWidthXl = 3; // A larger border size. Used for lines in focus, and the bottom chart container line.
export const SizeBorderWidthXxl = 4; // The largest border size. Used for the top chart container line.
export const SizeFontSizeXs = 12;
export const SizeFontSizeS = 14;
export const SizeFontSizeM = 16;
export const SizeFontSizeL = 19;
export const SizeFontSizeXl = 23;
export const SizeFontSizeXxl = 28;
export const SizeFontSizeXxxl = 34;
export const SizeFontSizeXxxxl = 41;
export const SizeFontSizeXxxxxl = 49;
export const SizeSpaceXxxxs = 3;
export const SizeSpaceXxxs = 5;
export const SizeSpaceXxs = 7;
export const SizeSpaceXs = 11;
export const SizeSpaceS = 16;
export const SizeSpaceM = 24;
export const SizeSpaceL = 36;
export const SizeSpaceXl = 54;
export const SizeSpaceXxl = 81;
export const SizeSpaceXxxl = 122;
export const SizeSpaceXxxxl = 183;
export const SizeSpaceXxxxxl = 275;
export const SizeMaxContentWidth = 1440;
export const SizeMinContentWidth = 480;
export const SizeBreakpointXs = 480;
export const SizeBreakpointSm = 640;
export const SizeBreakpointMd = 960;
export const SizeBreakpointLg = 1200;
export const SizeBreakpointXl = 1440;
export const SizeBorderRadiusBase = 1;
export const SizeBorderRadiusBigger = 4;
export const MetaProjectTitle = "PREVIEW"; // Project title
export const MetaVersion = "v1.0-WIP"; // Version
export const MetaProjectSubtitle = "Data Design Language";
export const MetaStyleRepoUrl = "preview.auswaertiges-amt.de/data-design-language";
export const MetaLastUpdated = 1986; // Last updated
export const MetaAuthors = "Moritz Stefaner / Truth & Beauty with Flavio Gortana"; // Authors
export const EffectShadowS = {"x":1,"y":1,"blur":2,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectShadowM = {"x":1,"y":1,"blur":3,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectShadowL = {"x":2,"y":2,"blur":6,"spread":0,"color":"#00000033","type":"dropShadow"};
export const EffectShadowXl = {"color":"#00000033","type":"dropShadow","x":2,"y":2,"blur":15,"spread":0};