export const SizeParameterFontSizeScaleFactor = 1.2;
export const SizeParameterFontSizeScaleFactorBelowOne = 1.15;
export const SizeParameterFontSizeBase = 16;
export const SizeParameterSpaceScaleFactor = 1.5;
export const SizeParameterSpaceScaleFactorBelowOne = 1.5;
export const SizeParameterSpaceBase = 24;
export const SizeChartWidth = 920;
export const SizeViewportLimit = 1440;
export const SizeMetaLabel = "Large";
export const SizeBorderWidthS = 0.5; // The smallest border size. Used for gridlines.
export const SizeBorderWidthM = 1; // The default border size. Used for axes borders, default data lines.
export const SizeBorderWidthL = 2; // A larger border size. Used for borders between filled elements.
export const SizeBorderWidthXl = 3; // A larger border size. Used for lines in focus, and the bottom chart container line.
export const SizeBorderWidthXxl = 4; // The largest border size. Used for the top chart container line.
export const SizeFontSizeXs = 12;
export const SizeFontSizeS = 14;
export const SizeFontSizeM = 16;
export const SizeFontSizeL = 19;
export const SizeFontSizeXl = 23;
export const SizeFontSizeXxl = 28;
export const SizeFontSizeXxxl = 34;
export const SizeFontSizeXxxxl = 41;
export const SizeFontSizeXxxxxl = 49;
export const SizeSpaceXxxxs = 3;
export const SizeSpaceXxxs = 5;
export const SizeSpaceXxs = 7;
export const SizeSpaceXs = 11;
export const SizeSpaceS = 16;
export const SizeSpaceM = 24;
export const SizeSpaceL = 36;
export const SizeSpaceXl = 54;
export const SizeSpaceXxl = 81;
export const SizeSpaceXxxl = 122;
export const SizeSpaceXxxxl = 183;
export const SizeSpaceXxxxxl = 275;
export const TypographyStyleBase = {"fontFamily":"Lato","fontWeight":400,"lineHeight":"160%","fontSize":16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // The default text style.
export const TypographyStyleHuge = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"115%","fontSize":28,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for summary statistics, large numbers, etc.
export const TypographyStyleLarge = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"115%","fontSize":23,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for the title of a chart.
export const TypographyStyleMajorPrimary = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"140%","fontSize":16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for legend main labels, as well as individual value annotations.
export const TypographyStyleMajorSecondary = {"fontFamily":"Lato","fontWeight":400,"lineHeight":"140%","fontSize":16,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for secondary legend labels, description, and the chart subtitle.
export const TypographyStyleMinorPrimary = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"115%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for smaller annotations in charts.
export const TypographyStyleMinorSecondary = {"fontFamily":"Lato","fontWeight":400,"lineHeight":"140%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for tick labels, secondary annotations, footer text.