export const SizeParameterFontSizeScaleFactor = 1.2;
export const SizeParameterFontSizeScaleFactorBelowOne = 1.1;
export const SizeParameterFontSizeBase = 14;
export const SizeParameterSpaceScaleFactor = 1.33;
export const SizeParameterSpaceScaleFactorBelowOne = 1.5;
export const SizeParameterSpaceBase = 14;
export const SizeChartWidth = 480;
export const SizeViewportLimit = 480;
export const SizeMetaLabel = "Small";
export const SizeBorderWidthS = 0.5; // The smallest border size. Used for gridlines.
export const SizeBorderWidthM = 1; // The default border size. Used for axes borders, default data lines.
export const SizeBorderWidthL = 1.5; // A larger border size. Used for borders between filled elements.
export const SizeBorderWidthXl = 2; // A larger border size. Used for lines in focus, and the bottom chart container line.
export const SizeBorderWidthXxl = 3; // The largest border size. Used for the top chart container line.
export const SizeFontSizeXs = 12;
export const SizeFontSizeS = 13;
export const SizeFontSizeM = 14;
export const SizeFontSizeL = 17;
export const SizeFontSizeXl = 20;
export const SizeFontSizeXxl = 24;
export const SizeFontSizeXxxl = 29;
export const SizeFontSizeXxxxl = 35;
export const SizeFontSizeXxxxxl = 42;
export const SizeSpaceXxxxs = 2;
export const SizeSpaceXxxs = 3;
export const SizeSpaceXxs = 4;
export const SizeSpaceXs = 6;
export const SizeSpaceS = 9;
export const SizeSpaceM = 14;
export const SizeSpaceL = 19;
export const SizeSpaceXl = 25;
export const SizeSpaceXxl = 33;
export const SizeSpaceXxxl = 44;
export const SizeSpaceXxxxl = 59;
export const SizeSpaceXxxxxl = 78;
export const TypographyStyleBase = {"fontFamily":"Lato","fontWeight":400,"lineHeight":"160%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // The default text style.
export const TypographyStyleHuge = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"115%","fontSize":24,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for summary statistics, large numbers, etc.
export const TypographyStyleLarge = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"115%","fontSize":20,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for the title of a chart.
export const TypographyStyleMajorPrimary = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"140%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for legend main labels, as well as individual value annotations.
export const TypographyStyleMajorSecondary = {"fontFamily":"Lato","fontWeight":400,"lineHeight":"140%","fontSize":14,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for secondary legend labels, description, and the chart subtitle.
export const TypographyStyleMinorPrimary = {"fontFamily":"Lato","fontWeight":700,"lineHeight":"115%","fontSize":13,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for smaller annotations in charts.
export const TypographyStyleMinorSecondary = {"fontFamily":"Lato","fontWeight":400,"lineHeight":"140%","fontSize":13,"letterSpacing":"0%","paragraphSpacing":8,"textDecoration":"none","textCase":"none"}; // Used for tick labels, secondary annotations, footer text.