export const ColorMetaLabel = "Light";
export const ColorBlendModeAdditive = "multiply";
export const ColorBlendModeMax = "darken";
export const ColorBackgroundBase = "#ffffff"; // The default light background color, used e.g. as a backdrop for charts or cards.
export const ColorBackgroundWeaker = "#f5f7f7"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorBackgroundWeakest = "#dce0e3"; // A shaded background color, used e.g. as a backdrop in containers.
export const ColorForegroundBase = "#1b1e20"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorForegroundWeak = "#616a72"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorForegroundWeaker = "#99a4ac"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorForegroundWeakest = "#dce0e3";
export const ColorThemeWeaker = "#316f91"; // Weaker version of theme color
export const ColorThemeBase = "#155375"; // Main theme color, usually the brand color.
export const ColorThemeStronger = "#0e3950"; // Stronger version of theme color
export const ColorFunctionalAccent = "#c0ce6b"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalFilteredOut = "#bec5c9"; // Used for visual marks in charts that have been filtered out.
export const ColorFunctionalFocus = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalNotAvailable = "#b2b2b2"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorFunctionalLink = "#1c4c64"; // Used for links.
export const ColorCategoryBase0 = "#489ac6";
export const ColorCategoryBase1 = "#8a973d";
export const ColorCategoryBase2 = "#ca7d34";
export const ColorCategoryBase99 = "#a6acb1";
export const ColorCategoryWeaker0 = "#8acffa";
export const ColorCategoryWeaker1 = "#c0ce6b";
export const ColorCategoryWeaker2 = "#f5b985";
export const ColorCategoryWeaker99 = "#c1c7cc";
export const ColorCategoryStronger0 = "#286485";
export const ColorCategoryStronger1 = "#59641b";
export const ColorCategoryStronger2 = "#88501a";
export const ColorCategoryStronger99 = "#72787c";
export const ColorCategoryWeakest0 = "#c8e7fd";
export const ColorCategoryWeakest1 = "#dceb84";
export const ColorCategoryWeakest2 = "#f9ddc5";
export const ColorCategoryStrongest0 = "#123446";
export const ColorCategoryStrongest1 = "#2e340a";
export const ColorCategoryStrongest2 = "#482909";
export const ColorDivergingNegative1 = "#ffffff"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorDivergingNegative2 = "#ffffff"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorDivergingNeutral = "#dce0e3"; // Third step in the base diverging color scale, used for zero or data median.
export const ColorDivergingPositive1 = "#ffffff"; // Fourth step in the base diverging color scale, used for values higher than zero (or data median).
export const ColorDivergingPositive2 = "#ffffff"; // Fifth step in the base diverging color scale, used for the highest (most positive) value. 
export const ColorComplementaryWeaker = "#ffffff"; // Weaker version of complementary color.
export const ColorComplementaryBase = "#ffffff"; // Main complementary color.
export const ColorComplementaryStronger = "#ffffff"; // Stronger version of complementary color.
export const ColorSequential0 = "#ffffff";
export const ColorSequential1 = "#ffffff";
export const ColorSequential2 = "#ffffff";
export const ColorSequential3 = "#ffffff";
export const ColorSequentialPositive0 = "#ffffff"; // First step in the base (theme) sequential color scale, used for the lowest value. 
export const ColorSequentialPositive1 = "#ffffff"; // Second step in the base (theme) sequential color scale.
export const ColorSequentialPositive2 = "#ffffff"; // Thirs step in the base (theme) sequential color scale.
export const ColorSequentialPositive3 = "#ffffff"; // Third and final step in the base (theme) sequential color scale.
export const ColorSequentialNegative0 = "#ffffff";
export const ColorSequentialNegative1 = "#ffffff";
export const ColorSequentialNegative2 = "#ffffff";
export const ColorSequentialNegative3 = "#ffffff";