export const ColorMetaLabel = "Light";
export const ColorBlendModeAdditive = "multiply";
export const ColorBlendModeMax = "darken";
export const ColorBackgroundBase = "#ffffff"; // The default light background color, used e.g. as a backdrop for charts or cards.
export const ColorBackgroundWeaker = "#f6fafe"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorBackgroundWeakest = "#dde3e8"; // A shaded background color, used e.g. as a backdrop in containers.
export const ColorForegroundBase = "#171d21"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorForegroundWeaker = "#595f63"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorForegroundWeakest = "#a6acb1"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorTextBase = "#191919"; // Default text color for strong background contrast.
export const ColorTextWeaker = "#595f63"; // Text color with weaker background contrast.
export const ColorTextInvertedBase = "#f8f8f8";
export const ColorTextInvertedWeaker = "#abafb0";
export const ColorThemeWeaker = "#489ac6"; // Weaker version of theme color
export const ColorThemeBase = "#1c4c64"; // Main theme color, usually the brand color.
export const ColorThemeStronger = "#123446"; // Stronger version of theme color
export const ColorFunctionalAccent = "#c0ce6b"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalFilteredOut = "#bec5c9"; // Used for visual marks in charts that have been filtered out.
export const ColorFunctionalFocus = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalNotAvailable = "#b2b2b2"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorFunctionalLink = "#1c4c64"; // Used for links.
export const ColorCategoryBase0 = "#297cb5";
export const ColorCategoryBase1 = "#905ea7";
export const ColorCategoryBase2 = "#de5f4a";
export const ColorCategoryBase3 = "#ffa81b";
export const ColorCategoryBase4 = "#51a27c";
export const ColorCategoryBase5 = "#9da61d";
export const ColorCategoryBase99 = "#9ea9b5";
export const ColorCategoryWeaker0 = "#83bad9";
export const ColorCategoryWeaker1 = "#b386c8";
export const ColorCategoryWeaker2 = "#e38c7c";
export const ColorCategoryWeaker3 = "#f8c975";
export const ColorCategoryWeaker4 = "#83c0a4";
export const ColorCategoryWeaker5 = "#ced56d";
export const ColorCategoryWeaker99 = "#c0c8d2";
export const ColorCategoryStronger0 = "#0161a3";
export const ColorCategoryStronger1 = "#492658";
export const ColorCategoryStronger2 = "#a72817";
export const ColorCategoryStronger3 = "#b26d00";
export const ColorCategoryStronger4 = "#0b5932";
export const ColorCategoryStronger5 = "#565d00";
export const ColorCategoryStronger99 = "#6b7581";
export const ColorDivergingNegative1 = "#e98676"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorDivergingNegative2 = "#a12917"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorDivergingNeutral = "#dde3e8"; // Third step in the base diverging color scale, used for zero or data median.
export const ColorDivergingPositive1 = "#79abbc"; // Fourth step in the base diverging color scale, used for values higher than zero (or data median).
export const ColorDivergingPositive2 = "#0e3e63"; // Fifth step in the base diverging color scale, used for the highest (most positive) value. 
export const ColorComplementaryWeaker = "#e98676"; // Weaker version of complementary color.
export const ColorComplementaryBase = "#dc6454"; // Main complementary color.
export const ColorComplementaryStronger = "#a12917"; // Stronger version of complementary color.
export const ColorSequential0 = "#c3d6dc";
export const ColorSequential1 = "#79abbc";
export const ColorSequential2 = "#377796";
export const ColorSequential3 = "#0e3e63";
export const ColorSequentialPositive0 = "#c3d6dc"; // First step in the base (theme) sequential color scale, used for the lowest value. 
export const ColorSequentialPositive1 = "#79abbc"; // Second step in the base (theme) sequential color scale.
export const ColorSequentialPositive2 = "#377796"; // Thirs step in the base (theme) sequential color scale.
export const ColorSequentialPositive3 = "#0e3e63"; // Third and final step in the base (theme) sequential color scale.
export const ColorSequentialNegative0 = "#fbc8bf";
export const ColorSequentialNegative1 = "#e98676";
export const ColorSequentialNegative2 = "#c9513f";
export const ColorSequentialNegative3 = "#a12917";