export const ColorMetaLabel = "Dark";
export const ColorBlendModeAdditive = "screen";
export const ColorBlendModeMax = "lighten";
export const ColorBackgroundBase = "#202020";
export const ColorBackgroundWeaker = "#303030"; // slightly shaded background
export const ColorBackgroundWeakest = "#666666";
export const ColorForegroundBase = "#eeeeee";
export const ColorForegroundWeaker = "#aaaaaa";
export const ColorForegroundWeakest = "#777777";
export const ColorTextWeaker = "#aaaaaa";
export const ColorTextBase = "#dddddd";
export const ColorTextStronger = "#ffffff"; // Stronger text color for maximum background contrast.
export const ColorTextInvertedBase = "#191919";
export const ColorTextInvertedWeaker = "#6b7581";
export const ColorTextModelAspectClimate = "#ffcb01"; // Climate
export const ColorTextModelAspectConflict = "#fa5a6d"; // Category color "conflict"
export const ColorTextModelAspectScopeConditions = "#90d3fb"; // Scope conditions
export const ColorThemeBase = "#44a8c3";
export const ColorThemeWeaker = "#256f81";
export const ColorThemeStronger = "#83c3d4";
export const ColorModelAspectClimate = "#ffcb01"; // Climate
export const ColorModelAspectConflict = "#fa5a6d"; // Category color "conflict"
export const ColorModelAspectScopeConditions = "#90d3fb"; // Scope conditions
export const ColorFunctionalAccent = "#bfc4f9";
export const ColorFunctionalFocus = "#ffcb01";
export const ColorFunctionalNotAvailable = "#cccccc";
export const ColorFunctionalFilteredOut = "#474b69";
export const ColorFunctionalLink = "#c3d6dc"; // Used for links.
export const ColorCategoryStronger0 = "#83bad9";
export const ColorCategoryStronger1 = "#b386c8";
export const ColorCategoryStronger2 = "#e38c7c";
export const ColorCategoryStronger3 = "#f8c975";
export const ColorCategoryStronger4 = "#83c0a4";
export const ColorCategoryStronger5 = "#ced56d";
export const ColorCategoryStronger99 = "#c0c8d2";
export const ColorCategoryBase0 = "#22699a";
export const ColorCategoryBase1 = "#825497";
export const ColorCategoryBase2 = "#c85543";
export const ColorCategoryBase3 = "#dc9d38";
export const ColorCategoryBase4 = "#458a69";
export const ColorCategoryBase5 = "#7e8518";
export const ColorCategoryBase99 = "#9ea9b5";
export const ColorCategoryWeaker0 = "#124874";
export const ColorCategoryWeaker1 = "#613f70";
export const ColorCategoryWeaker2 = "#993d31";
export const ColorCategoryWeaker3 = "#a07730";
export const ColorCategoryWeaker4 = "#366d53";
export const ColorCategoryWeaker5 = "#575b20";
export const ColorCategoryWeaker99 = "#6b7581";
export const ColorComplementaryBase = "#cc4233"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorComplementaryWeaker = "#832521"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorComplementaryStronger = "#da5c4b"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorDivergingPositive1 = "#256f81";
export const ColorDivergingPositive2 = "#66b5cb";
export const ColorDivergingNeutral = "#2c343e";
export const ColorDivergingNegative1 = "#832521";
export const ColorDivergingNegative2 = "#da5c4b";
export const ColorSequential0 = "#175462";
export const ColorSequential1 = "#348ba1";
export const ColorSequential2 = "#66b5cb";
export const ColorSequential3 = "#9ed0dd";
export const ColorSequentialPositive0 = "#175462";
export const ColorSequentialPositive1 = "#348ba1";
export const ColorSequentialPositive2 = "#66b5cb";
export const ColorSequentialPositive3 = "#9ed0dd";
export const ColorSequentialNegative0 = "#601817";
export const ColorSequentialNegative1 = "#a7332a";
export const ColorSequentialNegative2 = "#da5c4b";
export const ColorSequentialNegative3 = "#f38c7c";