export const ColorMetaLabel = "Light";
export const ColorBlendModeAdditive = "multiply";
export const ColorBlendModeMax = "darken";
export const ColorBackgroundBase = "#ffffff"; // The default light background color, used e.g. as a backdrop for charts or cards.
export const ColorBackgroundWeaker = "#f5f7f7"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorBackgroundWeakest = "#dce0e3"; // A shaded background color, used e.g. as a backdrop in containers.
export const ColorForegroundBase = "#1b1e20"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorForegroundWeak = "#616a72"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorForegroundWeaker = "#99a4ac"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorForegroundWeakest = "#dce0e3";
export const ColorThemeWeaker = "#316f91"; // Weaker version of theme color
export const ColorThemeBase = "#155375"; // Main theme color, usually the brand color.
export const ColorThemeStronger = "#0e3950"; // Stronger version of theme color
export const ColorFunctionalAccent = "#c0ce6b"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalFilteredOut = "#bec5c9"; // Used for visual marks in charts that have been filtered out.
export const ColorFunctionalFocus = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorFunctionalNotAvailable = "#b2b2b2"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorFunctionalLink = "#1c4c64"; // Used for links.
export const ColorCategoryBase0 = "#c94c24";
export const ColorCategoryBase1 = "#58cbd3";
export const ColorCategoryBase2 = "#f4bd49";
export const ColorCategoryBase3 = "#ffa81b";
export const ColorCategoryBase4 = "#51a27c";
export const ColorCategoryBase5 = "#9da61d";
export const ColorCategoryBase99 = "#ffffff";
export const ColorCategoryWeaker0 = "#83bad9";
export const ColorCategoryWeaker1 = "#b386c8";
export const ColorCategoryWeaker2 = "#e38c7c";
export const ColorCategoryWeaker3 = "#f8c975";
export const ColorCategoryWeaker4 = "#83c0a4";
export const ColorCategoryWeaker5 = "#ced56d";
export const ColorCategoryWeaker99 = "#ffffff";
export const ColorCategoryStronger0 = "#0161a3";
export const ColorCategoryStronger1 = "#492658";
export const ColorCategoryStronger2 = "#a72817";
export const ColorCategoryStronger3 = "#b26d00";
export const ColorCategoryStronger4 = "#0b5932";
export const ColorCategoryStronger5 = "#565d00";
export const ColorCategoryStronger99 = "#ffffff";
export const ColorDivergingNegative1 = "#ffffff"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorDivergingNegative2 = "#ffffff"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorDivergingNeutral = "#dce0e3"; // Third step in the base diverging color scale, used for zero or data median.
export const ColorDivergingPositive1 = "#ffffff"; // Fourth step in the base diverging color scale, used for values higher than zero (or data median).
export const ColorDivergingPositive2 = "#ffffff"; // Fifth step in the base diverging color scale, used for the highest (most positive) value. 
export const ColorComplementaryWeaker = "#ffffff"; // Weaker version of complementary color.
export const ColorComplementaryBase = "#ffffff"; // Main complementary color.
export const ColorComplementaryStronger = "#ffffff"; // Stronger version of complementary color.
export const ColorSequential0 = "#ffffff";
export const ColorSequential1 = "#ffffff";
export const ColorSequential2 = "#ffffff";
export const ColorSequential3 = "#ffffff";
export const ColorSequentialPositive0 = "#ffffff"; // First step in the base (theme) sequential color scale, used for the lowest value. 
export const ColorSequentialPositive1 = "#ffffff"; // Second step in the base (theme) sequential color scale.
export const ColorSequentialPositive2 = "#ffffff"; // Thirs step in the base (theme) sequential color scale.
export const ColorSequentialPositive3 = "#ffffff"; // Third and final step in the base (theme) sequential color scale.
export const ColorSequentialNegative0 = "#ffffff";
export const ColorSequentialNegative1 = "#ffffff";
export const ColorSequentialNegative2 = "#ffffff";
export const ColorSequentialNegative3 = "#ffffff";